majors = {
"UND": "Undeclared",
"UNON": "Non Degree",
"ANTH": "Anthropology",
"APPH": "Applied Physics",
"ART": "Art",
"ARTG": "Art And Design: Games And Playable Media",
"ARTH": "See History Of Art And Visual Culture",
"BENG": "Bioengineering",
"BIOC": "Biochemistry And Molecular Biology",
"BINF": "Bioinformatics",
"BIOL": "Biology",
"BMEC": "Business Management Economics",
"CHEM": "Chemistry",
"CLST": "Classical Studies",
"CMMU": "Community Studies",
"CMPE": "Computer Engineering",
"CMPS": "Computer Science",
"CMPG": "Computer Science: Computer Game Design",
"COGS": "Cognitive Science",
"CRES": "Critical Race And Ethnic Studies",
"EART": "Earth Sciences",
"ECEV": "Ecology And Evolution",
"ECON": "Economics",
"EE": "Electrical Engineering", 
"ENVS": "Environmental Studies",
"FMST": "Feminist Studies",
"FIDM": "Film And Digital Media",
"GMST": "German Studies",
"GLEC": "Global Economics",
"HBIO": "Human Biology",
"HIS": "History",
"HAVC": "History Of Art And Visual Culture",
"ITST": "Italian Studies",
"JWST": "Jewish Studies",
"LANG": "Language Studies",
"LALS": "Latin American And Latino Studies",
"LGST": "Legal Studies",
"LING": "Linguistics",
"LIT": "Literature",
"MABI": "Marine Biology",
"MATH": "Mathematics",
"MCDB": "Molecular, Cell, And Developmental Biology",
"MUSC": "Music", "NDT": "Network And Digital Technology",
"NBIO": "Neuroscience",
"PHIL": "Philosophy",
"PHYE": "Physics Education",
"PHYS": "Physics",
"ASPH": "Physics (astrophysics)",
"PLNT": "Plant Sciences", 
"POLI": "Politics",
"PSYC": "Psychology",
"ROBO": "Robotics Engineering",
"SOCI": "Sociology",
"SPST": "Spanish Studies",
"TIM": "Technology And Information Management",
"THEA": "Theater Arts",
"PRFM": "Pre-film And Digital Media",
"XESA": "Earth Sciences/anthropology",
"XEBI": "Environmental Studies/biology",
"XEEA": "Environmental Studies/earth Sciences",
"XEEC": "Environmental Studies/economics",
"XEMA": "Economics/mathematics",
"XLPT": "Latin American And Latino Studies/politics",
"XLSY": "Latin American And Latino Studies/sociology" }

result = {"values": []}

for abbrev, major in majors.items():
    synonyms = []
    synonyms.append(major)
    synonyms.append(abbrev.lower())
    result['values'].append({'id': abbrev, 'name':{'value':major, 'synonyms':synonyms}})

f = open("result.txt", "w")
f.write(str(result).replace("'", "\""))
f.close()